# Generated by Django 5.1.2 on 2025-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStore',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
